# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/ipc/protos/bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'core/ipc/protos/bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63ore/ipc/protos/bridge.proto\x12\x06\x62ridge\"\x1c\n\rConfigRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"U\n\x10\x43onfigSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nvalue_type\x18\x03 \x01(\t\x12\x11\n\tis_secret\x18\x04 \x01(\x08\"\x98\x01\n\x0e\x43onfigResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x34\n\x07\x63onfigs\x18\x03 \x03(\x0b\x32#.bridge.ConfigResponse.ConfigsEntry\x1a.\n\x0c\x43onfigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x10SubscribeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"u\n\nTaskUpdate\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x10\n\x08\x61ssignee\x18\x04 \x01(\t\x12\x12\n\nevent_type\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"7\n\x0e\x43ommandRequest\x12\x14\n\x0c\x63ommand_type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"3\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x0fSnapshotRequest\x12\x13\n\x0binterval_ms\x18\x01 \x01(\x05\"+\n\x08Snapshot\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32\xca\x02\n\x06\x42ridge\x12:\n\tGetConfig\x12\x15.bridge.ConfigRequest\x1a\x16.bridge.ConfigResponse\x12=\n\tSetConfig\x12\x18.bridge.ConfigSetRequest\x1a\x16.bridge.ConfigResponse\x12\x42\n\x10SubscribeToTasks\x12\x18.bridge.SubscribeRequest\x1a\x12.bridge.TaskUpdate0\x01\x12\x41\n\x0e\x45xecuteCommand\x12\x16.bridge.CommandRequest\x1a\x17.bridge.CommandResponse\x12>\n\x0fStreamSnapshots\x12\x17.bridge.SnapshotRequest\x1a\x10.bridge.Snapshot0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.ipc.protos.bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGRESPONSE_CONFIGSENTRY']._loaded_options = None
  _globals['_CONFIGRESPONSE_CONFIGSENTRY']._serialized_options = b'8\001'
  _globals['_CONFIGREQUEST']._serialized_start=40
  _globals['_CONFIGREQUEST']._serialized_end=68
  _globals['_CONFIGSETREQUEST']._serialized_start=70
  _globals['_CONFIGSETREQUEST']._serialized_end=155
  _globals['_CONFIGRESPONSE']._serialized_start=158
  _globals['_CONFIGRESPONSE']._serialized_end=310
  _globals['_CONFIGRESPONSE_CONFIGSENTRY']._serialized_start=264
  _globals['_CONFIGRESPONSE_CONFIGSENTRY']._serialized_end=310
  _globals['_SUBSCRIBEREQUEST']._serialized_start=312
  _globals['_SUBSCRIBEREQUEST']._serialized_end=349
  _globals['_TASKUPDATE']._serialized_start=351
  _globals['_TASKUPDATE']._serialized_end=468
  _globals['_COMMANDREQUEST']._serialized_start=470
  _globals['_COMMANDREQUEST']._serialized_end=525
  _globals['_COMMANDRESPONSE']._serialized_start=527
  _globals['_COMMANDRESPONSE']._serialized_end=578
  _globals['_SNAPSHOTREQUEST']._serialized_start=580
  _globals['_SNAPSHOTREQUEST']._serialized_end=618
  _globals['_SNAPSHOT']._serialized_start=620
  _globals['_SNAPSHOT']._serialized_end=663
  _globals['_BRIDGE']._serialized_start=666
  _globals['_BRIDGE']._serialized_end=996
# @@protoc_insertion_point(module_scope)
