# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from core.ipc.protos import bridge_pb2 as core_dot_ipc_dot_protos_dot_bridge__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in core/ipc/protos/bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BridgeStub(object):
    """The Bridge service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommand = channel.unary_unary(
                '/aas.ipc.Bridge/ExecuteCommand',
                request_serializer=core_dot_ipc_dot_protos_dot_bridge__pb2.CommandRequest.SerializeToString,
                response_deserializer=core_dot_ipc_dot_protos_dot_bridge__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamSnapshots = channel.unary_stream(
                '/aas.ipc.Bridge/StreamSnapshots',
                request_serializer=core_dot_ipc_dot_protos_dot_bridge__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=core_dot_ipc_dot_protos_dot_bridge__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.SubscribeToTasks = channel.unary_stream(
                '/aas.ipc.Bridge/SubscribeToTasks',
                request_serializer=core_dot_ipc_dot_protos_dot_bridge__pb2.TaskSubscriptionRequest.SerializeToString,
                response_deserializer=core_dot_ipc_dot_protos_dot_bridge__pb2.TaskUpdate.FromString,
                _registered_method=True)


class BridgeServicer(object):
    """The Bridge service definition.
    """

    def ExecuteCommand(self, request, context):
        """Sends a high-level command from AAS to Maelstrom
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSnapshots(self, request, context):
        """Streams game state snapshots from Maelstrom to AAS
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToTasks(self, request, context):
        """Subscribe to real-time task updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=core_dot_ipc_dot_protos_dot_bridge__pb2.CommandRequest.FromString,
                    response_serializer=core_dot_ipc_dot_protos_dot_bridge__pb2.CommandResponse.SerializeToString,
            ),
            'StreamSnapshots': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSnapshots,
                    request_deserializer=core_dot_ipc_dot_protos_dot_bridge__pb2.SnapshotRequest.FromString,
                    response_serializer=core_dot_ipc_dot_protos_dot_bridge__pb2.SnapshotResponse.SerializeToString,
            ),
            'SubscribeToTasks': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToTasks,
                    request_deserializer=core_dot_ipc_dot_protos_dot_bridge__pb2.TaskSubscriptionRequest.FromString,
                    response_serializer=core_dot_ipc_dot_protos_dot_bridge__pb2.TaskUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aas.ipc.Bridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aas.ipc.Bridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bridge(object):
    """The Bridge service definition.
    """

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aas.ipc.Bridge/ExecuteCommand',
            core_dot_ipc_dot_protos_dot_bridge__pb2.CommandRequest.SerializeToString,
            core_dot_ipc_dot_protos_dot_bridge__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aas.ipc.Bridge/StreamSnapshots',
            core_dot_ipc_dot_protos_dot_bridge__pb2.SnapshotRequest.SerializeToString,
            core_dot_ipc_dot_protos_dot_bridge__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aas.ipc.Bridge/SubscribeToTasks',
            core_dot_ipc_dot_protos_dot_bridge__pb2.TaskSubscriptionRequest.SerializeToString,
            core_dot_ipc_dot_protos_dot_bridge__pb2.TaskUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
